apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: label-demo
  name: label-demo
spec:
  nodeSelector:
    CKA: "true"
  containers:
  - image: nginx
    name: label-demo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
