apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: demo
  name: demo
spec:
  containers:
  - image: nginx
    name: demo
    resources: {}
  - image: redis
    name: database
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
