apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: lauren
  name: lauren
spec:
  containers:
  - image: nginx
    name: lauren
    resources: {}
    volumeMounts:
    - name: demo
      mountPath: /usr/share/nginx/html
  initContainers:
  - name: sam-init
    image: busybox:1.28
    command: ['sh', '-c', 'echo "hello world" | tee /tmp/index.html']
    volumeMounts:
    - name: demo
      mountPath: "/tmp/"
  dnsPolicy: ClusterFirst
  volumes:
  - name: demo
    emptyDir: {}

  restartPolicy: Always
status: {}
